"""link_past_data_to_chunks

Revision ID: 0ff8c058d77d
Revises: e144835b6ff8
Create Date: 2026-01-14 19:37:56.427625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ff8c058d77d'
down_revision: Union[str, Sequence[str], None] = 'e144835b6ff8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_past_data_s3_key', table_name='past_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_past_data_s3_key', 'past_data', ['s3_key'], unique=False)
    # ### end Alembic commands ###
