"""create_initial_tables

Revision ID: 43b2c7e3c6bb
Revises: 
Create Date: 2026-01-12 05:07:26.029657

"""
from typing import Sequence, Union
import pgvector  
from pgvector.sqlalchemy import Vector 
import sqlalchemy as sa
from alembic import op  


# revision identifiers, used by Alembic.
revision: str = '43b2c7e3c6bb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('primary_industry', sa.Text(), nullable=True),
    sa.Column('secondary_industry', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('passcode', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('hypothesis_type', sa.String(), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('evalulated', sa.Boolean(), nullable=True),
    sa.Column('hypotheses_output', sa.Text(), nullable=True),
    sa.Column('hypotheses_output_score', sa.Integer(), nullable=True),
    sa.Column('hypothesis_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviewee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_industry', sa.Text(), nullable=True),
    sa.Column('customer_experience', sa.Text(), nullable=True),
    sa.Column('customer_occupation', sa.Text(), nullable=True),
    sa.Column('customer_checked', sa.Boolean(), nullable=True),
    sa.Column('customers_output', sa.Text(), nullable=True),
    sa.Column('customers_output_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('interviewee_name', sa.String(), nullable=True),
    sa.Column('evaluated', sa.Boolean(), nullable=True),
    sa.Column('interviews_output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks')
    op.drop_table('interviews')
    op.drop_table('interviewee')
    op.drop_table('hypotheses')
    op.drop_table('teams')
    # ### end Alembic commands ###
