"""rename_evalulated_to_evaluated

Revision ID: 51e1ef9519a0
Revises: 48eca6561625
Create Date: 2026-01-13 20:54:24.061120

"""
from typing import Sequence, Union
import pgvector
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e1ef9519a0'
down_revision: Union[str, Sequence[str], None] = '48eca6561625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_chunks_interview_id_fkey', 'document_chunks', type_='foreignkey')
    op.drop_constraint('document_chunks_past_data_id_fkey', 'document_chunks', type_='foreignkey')
    op.drop_column('document_chunks', 'past_data_id')
    op.drop_column('document_chunks', 'interview_id')
    op.add_column('hypotheses', sa.Column('evaluated', sa.Boolean(), nullable=True))
    op.drop_column('hypotheses', 'evalulated')
    op.add_column('past_data', sa.Column('content', sa.Text(), nullable=True))
    op.add_column('past_data', sa.Column('data_type', sa.String(), nullable=True))
    op.add_column('past_data', sa.Column('outcome', sa.Text(), nullable=True))
    op.add_column('past_data', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.drop_column('past_data', 'interview_evaulation')
    op.drop_column('past_data', 'embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('past_data', sa.Column('embeddings', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.add_column('past_data', sa.Column('interview_evaulation', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('past_data', 'embedding')
    op.drop_column('past_data', 'outcome')
    op.drop_column('past_data', 'data_type')
    op.drop_column('past_data', 'content')
    op.add_column('hypotheses', sa.Column('evalulated', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('hypotheses', 'evaluated')
    op.add_column('document_chunks', sa.Column('interview_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('document_chunks', sa.Column('past_data_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('document_chunks_past_data_id_fkey', 'document_chunks', 'past_data', ['past_data_id'], ['id'])
    op.create_foreign_key('document_chunks_interview_id_fkey', 'document_chunks', 'interviews', ['interview_id'], ['id'])
    # ### end Alembic commands ###
