"""teams replace industries with industry

Revision ID: 51ed755c36cc
Revises: 43b2c7e3c6bb
Create Date: 2026-01-12 17:14:53.887231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '51ed755c36cc'
down_revision: Union[str, Sequence[str], None] = '43b2c7e3c6bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviewees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_industry', sa.Text(), nullable=True),
    sa.Column('customer_experience', sa.Text(), nullable=True),
    sa.Column('customer_occupation', sa.Text(), nullable=True),
    sa.Column('customer_checked', sa.Boolean(), nullable=True),
    sa.Column('customers_output', sa.Text(), nullable=True),
    sa.Column('customers_output_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('past_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('hypothesis_embedding', Vector(dim=1536), nullable=True),
    sa.Column('hypothesis_evaluation', sa.Text(), nullable=True),
    sa.Column('hypothesis_score', sa.Integer(), nullable=True),
    sa.Column('user_personas', sa.JSON(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('interview_evaulation', sa.Text(), nullable=True),
    sa.Column('hypotheses_output', sa.Text(), nullable=True),
    sa.Column('hypotheses_output_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('interviewee')
    op.add_column('document_chunks', sa.Column('past_data_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document_chunks', 'past_data', ['past_data_id'], ['id'])
    op.add_column('teams', sa.Column('industry', sa.Text(), nullable=True))
    op.drop_column('teams', 'primary_industry')
    op.drop_column('teams', 'passcode')
    op.drop_column('teams', 'secondary_industry')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('secondary_industry', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('passcode', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('teams', sa.Column('primary_industry', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('teams', 'industry')
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_column('document_chunks', 'past_data_id')
    op.create_table('interviewee',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('customer_industry', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_experience', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_occupation', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customer_checked', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('customers_output', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('customers_output_score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], name='interviewee_team_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='interviewee_pkey')
    )
    op.drop_table('past_data')
    op.drop_table('interviewees')
    # ### end Alembic commands ###
