"""sync_hypotheses_naming

Revision ID: 94af4635bcea
Revises: 6d646f352633
Create Date: 2026-01-14 18:57:35.698553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '94af4635bcea'
down_revision: Union[str, Sequence[str], None] = '6d646f352633'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_document_chunks_s3_key'), 'document_chunks', ['s3_key'], unique=False)
    op.add_column('hypotheses', sa.Column('type', sa.String(), nullable=True))
    op.add_column('hypotheses', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True))
    op.drop_column('hypotheses', 'hypothesis_embedding')
    op.drop_column('hypotheses', 'hypothesis_type')
    op.create_index(op.f('ix_past_data_s3_key'), 'past_data', ['s3_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_past_data_s3_key'), table_name='past_data')
    op.add_column('hypotheses', sa.Column('hypothesis_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('hypotheses', sa.Column('hypothesis_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), autoincrement=False, nullable=True))
    op.drop_column('hypotheses', 'embedding')
    op.drop_column('hypotheses', 'type')
    op.drop_index(op.f('ix_document_chunks_s3_key'), table_name='document_chunks')
    # ### end Alembic commands ###
