"""fix typo in position column

Revision ID: 9e4daabb4a17
Revises: 51e1ef9519a0
Create Date: 2026-01-14 16:30:20.786098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4daabb4a17'
down_revision: Union[str, Sequence[str], None] = '51e1ef9519a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ai_interviewees', sa.Column('position', sa.String(), nullable=True))
    op.drop_column('ai_interviewees', 'poition')
    op.drop_column('interviewees', 'customer_name')
    op.add_column('interviews', sa.Column('hypothesis_id', sa.String(), nullable=True))
    op.add_column('interviews', sa.Column('interviews_summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'interviews', 'hypotheses', ['hypothesis_id'], ['id'])
    op.drop_column('interviews', 'interviewee_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('interviewee_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'interviews_summary')
    op.drop_column('interviews', 'hypothesis_id')
    op.add_column('interviewees', sa.Column('customer_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('ai_interviewees', sa.Column('poition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('ai_interviewees', 'position')
    # ### end Alembic commands ###
