"""check_drift

Revision ID: d04124c9383b
Revises: 04cd76fca5c2
Create Date: 2026-01-14 18:46:07.551734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd04124c9383b'
down_revision: Union[str, Sequence[str], None] = '04cd76fca5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('hypothesis_id', sa.Integer(), nullable=True))
    op.add_column('interviews', sa.Column('interviews_summary', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'interviews', 'hypotheses', ['hypothesis_id'], ['id'])
    op.drop_column('interviews', 'interviewee_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('interviewee_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'interviews_summary')
    op.drop_column('interviews', 'hypothesis_id')
    # ### end Alembic commands ###
