"""link_past_data_to_chunks

Revision ID: e144835b6ff8
Revises: 9e911c39bd7d
Create Date: 2026-01-14 19:37:21.205343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e144835b6ff8'
down_revision: Union[str, Sequence[str], None] = '9e911c39bd7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('interview_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document_chunks', 'interviews', ['interview_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.drop_column('document_chunks', 'interview_id')
    # ### end Alembic commands ###
