"""changed hypothesis and team models

Revision ID: 0b3a51e4434f
Revises: a0a6746c4fb0
Create Date: 2026-01-16 16:32:50.295165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3a51e4434f'
down_revision: Union[str, Sequence[str], None] = 'a0a6746c4fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviewees', 'customer_experience')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviewees', sa.Column('customer_experience', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
