"""baseline

Revision ID: 292c245e22f1
Revises: 
Create Date: 2026-01-16 17:03:05.093525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '292c245e22f1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('past_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('data_type', sa.String(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('industry', sa.Text(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('hyp_type', sa.String(), nullable=True),
    sa.Column('hypothesis', sa.Text(), nullable=True),
    sa.Column('evaluated', sa.Boolean(), nullable=True),
    sa.Column('hypotheses_output', sa.Text(), nullable=True),
    sa.Column('hypotheses_output_score', sa.Integer(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('past_document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('past_data_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['past_data_id'], ['past_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_interviewees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hypothesis_id', sa.Integer(), nullable=True),
    sa.Column('company_type', sa.String(), nullable=True),
    sa.Column('market_segment', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('position', sa.String(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('outreach_methods', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviewees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('hypothesis_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_industry', sa.Text(), nullable=True),
    sa.Column('customer_occupation', sa.Text(), nullable=True),
    sa.Column('customer_checked', sa.Boolean(), nullable=True),
    sa.Column('customers_output', sa.Text(), nullable=True),
    sa.Column('customers_output_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('hypothesis_id', sa.Integer(), nullable=True),
    sa.Column('s3_key', sa.String(), nullable=True),
    sa.Column('evaluated', sa.Boolean(), nullable=True),
    sa.Column('interviews_summary', sa.Text(), nullable=True),
    sa.Column('interviews_output', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key')
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('interview_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.ForeignKeyConstraint(['interview_id'], ['interviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks')
    op.drop_table('interviews')
    op.drop_table('interviewees')
    op.drop_table('ai_interviewees')
    op.drop_table('past_document_chunks')
    op.drop_table('hypotheses')
    op.drop_table('teams')
    op.drop_table('past_data')
    # ### end Alembic commands ###
