"""automatic_schema_rebuild

Revision ID: 9b6aed29713a
Revises: 
Create Date: 2026-01-14 21:48:57.924442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6aed29713a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interviewees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.String(), nullable=True),
    sa.Column('hypothesis_id', sa.Integer(), nullable=True),
    sa.Column('customer_name', sa.String(), nullable=True),
    sa.Column('customer_industry', sa.Text(), nullable=True),
    sa.Column('customer_experience', sa.Text(), nullable=True),
    sa.Column('customer_occupation', sa.Text(), nullable=True),
    sa.Column('customer_checked', sa.Boolean(), nullable=True),
    sa.Column('customers_output', sa.Text(), nullable=True),
    sa.Column('customers_output_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interviewees')
    # ### end Alembic commands ###
