"""sync schema after merge

Revision ID: a0a6746c4fb0
Revises: d04124c9383b
Create Date: 2026-01-15 14:21:06.404794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a6746c4fb0'
down_revision: Union[str, Sequence[str], None] = 'd04124c9383b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)

    # --- Helper: Get columns and constraints for specific tables ---
    def get_cols(table):
        return [c['name'] for c in inspector.get_columns(table)]

    def get_fks(table):
        return [f['name'] for f in inspector.get_foreign_keys(table)]

    # --- 1. Tables: document_chunks ---
    chunks_cols = get_cols('document_chunks')
    if 'team_id' in chunks_cols:
        # If the FK exists, drop it first
        if 'document_chunks_team_id_fkey' in get_fks('document_chunks'):
            op.drop_constraint('document_chunks_team_id_fkey', 'document_chunks', type_='foreignkey')
        op.drop_column('document_chunks', 'team_id')
    
    if 's3_key' in chunks_cols:
        op.drop_column('document_chunks', 's3_key')

    # --- 2. Tables: hypotheses ---
    hyp_cols = get_cols('hypotheses')
    if 'hyp_type' not in hyp_cols:
        op.add_column('hypotheses', sa.Column('hyp_type', sa.String(), nullable=True))
    if 'type' in hyp_cols:
        op.drop_column('hypotheses', 'type')

    # --- 3. Tables: interviewees ---
    inter_cols = get_cols('interviewees')
    if 'hypothesis_id' not in inter_cols:
        op.add_column('interviewees', sa.Column('hypothesis_id', sa.Integer(), nullable=True))
    if 'customer_name' not in inter_cols:
        op.add_column('interviewees', sa.Column('customer_name', sa.String(), nullable=True))
    
    # Check if the FK already exists before creating
    if 'interviewees_hypothesis_id_fkey' not in get_fks('interviewees'):
        op.create_foreign_key(None, 'interviewees', 'hypotheses', ['hypothesis_id'], ['id'])

    # --- 4. Tables: past_data ---
    if 'outcome' in get_cols('past_data'):
        op.drop_column('past_data', 'outcome')

    # --- 5. Tables: past_document_chunks ---
    past_chunks_cols = get_cols('past_document_chunks')
    if 'team_id' in past_chunks_cols:
        if 'past_document_chunks_team_id_fkey' in get_fks('past_document_chunks'):
            op.drop_constraint('past_document_chunks_team_id_fkey', 'past_document_chunks', type_='foreignkey')
        op.drop_column('past_document_chunks', 'team_id')
    if 's3_key' in past_chunks_cols:
        op.drop_column('past_document_chunks', 's3_key')

    # --- 6. Tables: teams ---
    if 'status' in get_cols('teams'):
        op.drop_column('teams', 'status')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('past_document_chunks', sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('past_document_chunks', sa.Column('team_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('past_document_chunks_team_id_fkey', 'past_document_chunks', 'teams', ['team_id'], ['id'])
    op.create_index('ix_past_document_chunks_s3_key', 'past_document_chunks', ['s3_key'], unique=False)
    op.add_column('past_data', sa.Column('outcome', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_foreign_key('interviews_hypothesis_id_fkey', 'interviews', 'hypotheses', ['hypothesis_id'], ['id'], ondelete='SET NULL')
    #op.drop_constraint(None, 'interviewees', type_='foreignkey')
    op.drop_column('interviewees', 'customer_name')
    op.drop_column('interviewees', 'hypothesis_id')
    op.add_column('hypotheses', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('hypotheses', 'hyp_type')
    op.add_column('document_chunks', sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('document_chunks', sa.Column('team_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('document_chunks_team_id_fkey', 'document_chunks', 'teams', ['team_id'], ['id'])
    op.create_index('ix_document_chunks_s3_key', 'document_chunks', ['s3_key'], unique=False)
    # ### end Alembic commands ###
