"""sync schema after merge

Revision ID: a0a6746c4fb0
Revises: d04124c9383b
Create Date: 2026-01-15 14:21:06.404794

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a6746c4fb0'
down_revision: Union[str, Sequence[str], None] = 'd04124c9383b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_index('ix_document_chunks_s3_key', table_name='document_chunks')
    op.drop_constraint('document_chunks_team_id_fkey', 'document_chunks', type_='foreignkey')
    op.drop_column('document_chunks', 'team_id')
    op.drop_column('document_chunks', 's3_key')
    op.add_column('hypotheses', sa.Column('hyp_type', sa.String(), nullable=True))
    op.drop_column('hypotheses', 'type')
    op.add_column('interviewees', sa.Column('hypothesis_id', sa.Integer(), nullable=True))
    op.add_column('interviewees', sa.Column('customer_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'interviewees', 'hypotheses', ['hypothesis_id'], ['id'])
    op.drop_constraint('interviews_hypothesis_id_fkey', 'interviews', type_='foreignkey')
    op.create_foreign_key(None, 'interviews', 'hypotheses', ['hypothesis_id'], ['id'])
    op.drop_column('past_data', 'outcome')
    op.drop_index('ix_past_document_chunks_s3_key', table_name='past_document_chunks')
    op.drop_constraint('past_document_chunks_team_id_fkey', 'past_document_chunks', type_='foreignkey')
    op.drop_column('past_document_chunks', 'team_id')
    op.drop_column('past_document_chunks', 's3_key')
    op.drop_column('teams', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('past_document_chunks', sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('past_document_chunks', sa.Column('team_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('past_document_chunks_team_id_fkey', 'past_document_chunks', 'teams', ['team_id'], ['id'])
    op.create_index('ix_past_document_chunks_s3_key', 'past_document_chunks', ['s3_key'], unique=False)
    op.add_column('past_data', sa.Column('outcome', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.create_foreign_key('interviews_hypothesis_id_fkey', 'interviews', 'hypotheses', ['hypothesis_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'interviewees', type_='foreignkey')
    op.drop_column('interviewees', 'customer_name')
    op.drop_column('interviewees', 'hypothesis_id')
    op.add_column('hypotheses', sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('hypotheses', 'hyp_type')
    op.add_column('document_chunks', sa.Column('s3_key', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('document_chunks', sa.Column('team_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('document_chunks_team_id_fkey', 'document_chunks', 'teams', ['team_id'], ['id'])
    op.create_index('ix_document_chunks_s3_key', 'document_chunks', ['s3_key'], unique=False)
    # ### end Alembic commands ###
